name: CI/CD

on:
  push:
    branches:
      - main

jobs:
    test:
      runs-on: ubuntu-latest 
      steps:
      - name: CheckOut code 
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      - name: Run test
        run: php cdciTest.php

    deploy:
      runs-on: ubuntu-latest
      needs: test
      steps:
      - name: Deploy to Beget Hosting
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.BEGET_HOST }}
            username: ${{ secrets.BEGET_USERNAME }}
            password: ${{ secrets.BEGET_PASSWORD }}
            script: |
                cd ovdoviza.beget.tech/public_html
                git pull origin main